### ISSUE TITLE
Error running "gatsby develop" on fresh clone

### ISSUE THREAD

**Issue by ZBlocker655** [joeattardi/coffee-shop-starter#15]
I'm using your book, "Using Gatsby and Netlify CMS" to set up my new personal blog. 

I just tried to clone this repo and run first `npm install` followed by `gatsby develop`.  On the NPM install I got lots of deprecated package warnings, but here's what I get on the `gatsby develop` command:

```
... (snip)
info bootstrap finished - 18.717s
success run static queries - 0.034s - 1/1 29.13/s
success run page queries - 0.031s - 2/2 63.82/s

 ERROR

error:0308010C:digital envelope routines::unsupported
```

My setup:
- Windows 10
- Node version 18.10.0
- Gatsby version 2.23.7

**Comment by joeattardi** [comment]
Hm, what version of Node.js do you have? This may fix the problem:

```
export NODE_OPTIONS=--openssl-legacy-provider
```

**Comment by ZBlocker655** [comment]
I'm running 18.10.0, close to latest at this time, but I am on NVM so I can walk the version back - what version of Node were you using when you created this? 

Also are there any security implications to using the `openssl-legacy-provider` option?

**Comment by ZBlocker655** [comment]
Update: using that legacy SSL option worked!  I am still curious about the security question.

**Comment by joeattardi** [comment]
Not sure, probably not an issue since you're just running a local development server. In general it's usually a good idea to stick to the LTS versions of Node, the bleeding edge stuff can sometimes have issues.

What version did I use when creating this? Good question. It was over two years ago, probably whatever the LTS version was at the time.
